feat(unitTest): activate unit test before push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,15 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+[[ $(git rev-parse --abbrev-ref HEAD) =~ ^(main|dev) ]] \
+&& \
+    echo "Building unit tests..."
+    ./Tests/build.bat
 
-./Tests/build.bat
+    ./Tests/Win32/Release/UnitTests.exe -b -cm:Quiet -l:Error
 
-./Tests/Win32/Release/UnitTests.exe
+    [ $? -eq 0 ] && echo "All unit tests passed." || exit 1
+|| \
+    echo "Not on a branch where unit tests are required" \\
 
-[ $? -eq 0 ] && echo "All unit tests passed." || exit 1
+ exit 1
